# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shreya-mate"
client_id = "d2fd90610d0b292e8ba0ca086823769b"
application_url = "https://polar-moral-dallas-absolutely.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://polar-moral-dallas-absolutely.trycloudflare.com/auth/callback",
  "https://polar-moral-dallas-absolutely.trycloudflare.com/auth/shopify/callback",
  "https://polar-moral-dallas-absolutely.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-4cb07f3a.myshopify.com"
