# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Review Mate"
client_id = "4934c58427211856cfe456e5b638d4fc"
application_url = "https://waste-viewpicture-keyboards-rug.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://waste-viewpicture-keyboards-rug.trycloudflare.com/auth/callback",
  "https://waste-viewpicture-keyboards-rug.trycloudflare.com/auth/shopify/callback",
  "https://waste-viewpicture-keyboards-rug.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-review-ap.myshopify.com"
