# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "testing-mate"
client_id = "570095e20b1937221e5c687aaee9797e"
application_url = "https://managing-hardly-musicians-easier.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://managing-hardly-musicians-easier.trycloudflare.com/auth/callback",
  "https://managing-hardly-musicians-easier.trycloudflare.com/auth/shopify/callback",
  "https://managing-hardly-musicians-easier.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-review-ap.myshopify.com"
